"""Added ShortUrl Table and adjusted OriginalUrl table's column

Revision ID: 58c5a136d4f9
Revises: 574f93c72e3a
Create Date: 2026-04-16 19:24:31.512610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58c5a136d4f9'
down_revision: Union[str, Sequence[str], None] = '574f93c72e3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
